spring.jpa.hibernate.ddl-auto: create
spring.datasource.url: jdbc:mysql://localhost:3306/blogdb?serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: test
spring.jpa.generate-ddl: true
spring.data.jpa.repositories.enabled: true
spring.jpa.show-sql: true