#Init information
title: DevPub
subtitle: Рассказы разработчиков
phone: +7 903 666-44-55
email: mail@mail.ru
copyright: Тимиров Сергей
copyrightFrom: 2020

#Redis configuration
redis.datasource.url: ${REDIS_URL:redis://localhost:6379}

#MySQL configuration
spring.datasource.url: jdbc:${CLEARDB_DATABASE_URL:mysql://${LOGIN_PASS}@localhost:3307/blogdb?serverTimezone=UTC}
server.port: ${PORT_MYSQL:8080}

#JPA configuration
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.generate-ddl: false
spring.data.jpa.repositories.enabled: true
spring.jpa.show-sql: true

#Captcha settings
##Timeout deleting captcha in minutes
captcha.timeout: 10
##Length captcha codes
captcha.visible.length: 7
captcha.secret.length: 17

#Subdirectories config
subdir.name.length: 3
subdir.depth: 3

#Default directories for upload images
default.upload.dir: src/main/webapp/upload/
default.upload.temp.dir: src/main/webapp/temp/

#Max size uploaded image (Mb)
image.upload.max.size: 5

#Max size profile photo
profile.photo.height: 36
profile.photo.width: 36

#Mail service config
mail.protocol: smtp
mail.host: smtp.gmail.com
mail.port: 587
mail.username: skillbox.service
mail.password: SkillBox321
mail.smtp.auth: true
mail.starttls.enable: true
mail.debug: false