#Init information
title: DevPub
subtitle: Рассказы разработчиков
phone: +7 903 666-44-55
email: mail@mail.ru
copyright: Тимиров Сергей
copyrightFrom: 2020

#Redis configuration
redis.host: ec2-52-16-131-126.eu-west-1.compute.amazonaws.com
redis.port: 12019

#MySQL configuration
spring.datasource.url: jdbc:${CLEARDB_DATABASE_URL:mysql://bc96a3334a5591:397cceba@eu-cdbr-west-03.cleardb.net/heroku_05b79667752e77a?useUnicode=true&characterEncoding=utf-8&reconnect=true}
#spring.datasource.url: jdbc:mysql://localhost:3307/blogdb?serverTimezone=UTC
#spring.datasource.username: root
#spring.datasource.password: еуые
server.port: ${PORT:8080}

#JPA configuration
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.generate-ddl: false
spring.data.jpa.repositories.enabled: true
spring.jpa.show-sql: true

#Captcha settings
##Timeout deleting captcha in minutes
captcha.timeout: 10
##Length captcha codes
captcha.visible.length: 7
captcha.secret.length: 17

#Subdirectories config
subdir.name.length: 3
subdir.depth: 3

#Default directories for upload images
default.upload.dir: src/main/webapp/upload/

#Size upload image (Mb)
image.upload.max.size: 5

#Mail service config
mail.protocol: smtp
mail.host: smtp.gmail.com
mail.port: 587
mail.username: skillbox.service
mail.password: SkillBox321
mail.smtp.auth: true
mail.starttls.enable: true
mail.debug: false